"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g87d2024
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "skillberry-store-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

# `pip install skillberry-store-sdk[cli]` also installs the native `sbs` binary.
#
# The SDK itself stays a pure-Python library with no binary dependency, so it
# installs anywhere — that is why this is an extra rather than a hard dependency
# (docs/design/new_cli.md §4.6). Environment markers keep it to the platforms we
# publish wheels for: on anything else the extra resolves to nothing rather than
# failing the whole install, and the CLI comes from the store's own
# /cli/install.sh instead.
_CLI_PLATFORMS = [
    "(sys_platform == 'linux' and platform_machine in 'x86_64 aarch64')",
    "(sys_platform == 'darwin' and platform_machine in 'x86_64 arm64')",
    "(sys_platform == 'win32' and platform_machine in 'AMD64 x86_64')",
]
EXTRAS = {
    "cli": [
        "skillberry-store-cli; " + " or ".join(_CLI_PLATFORMS),
    ],
}

setup(
    name=NAME,
    version=VERSION,
    description="skillberry",
    author="Eran Raichstein",
    author_email="eranra@il.ibm.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "skillberry"],
    install_requires=REQUIRES,
    extras_require=EXTRAS,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    """,  # noqa: E501
    package_data={"skillberry_store_sdk": ["py.typed"]},
)
